version: '2.3'

services:
#  mongo1:
#    restart: always
#    image: mongo:3.4
#    hostname: mongo1
#    expose:
#      - "27017"
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo1:/data/db

  mysql1:
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./application/schemas/mysql.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - variables.env
    mem_limit: 8000000000
    cpu_count: 4
    cpu_percent: 75
    cpus: 4.0

  memcached:
    mem_limit: 500000000
    cpu_count: 1
    cpu_percent: 10
    cpus: 0.5

  #queue:
  #  container_name: spreadshare-queue1
  #  restart: always
  #  image: phalconphp/beanstalkd:1.10
  #  ports:
  #    - "11300:11300"
  #  volumes:
  #    - beanstalk:/var/lib/beanstalkd

  redis:
    mem_limit: 500000000
    cpu_count: 2
    cpu_percent: 25
    cpus: 1

  elasticsearch:
    mem_limit: 1000000000
    cpu_count: 2
    cpu_percent: 25
    cpus: 1

  app:
    ports:
      - "80:80"
      - "443:443"
    mem_limit: 2000000000
    cpu_count: 8
    cpu_percent: 75
    cpus: 4.0
    environment:
        PRODUCTION: 'true'
        DEVELOPMENT: 'false'
