version: '2.3'

services:
  mysql1:
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./application/schemas/mysql.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - variables.env
    mem_limit: 8000000000
    cpu_count: 4
    cpu_percent: 90
    cpus: 2.0

  redis:
    mem_limit: 200000000
    cpu_count: 2
    cpu_percent: 35
    cpus: 1

  app:
    ports:
      - "80:80"
      - "443:443"
    mem_limit: 2000000000
    cpu_count: 8
    cpu_percent: 95
    cpus: 2.0
    environment:
        BUILD_ENVIRONMENT: 'production'
        APPLICATION_ENV: 'production'
        HOST: 'beta.spreadshare.co'
        AUTH_CALLBACK: 'http://beta.spreadshare.co/login'
        WALLET: 'http://ec2-18-217-109-204.us-east-2.compute.amazonaws.com/'
        MAILGUN_KEY: 'key-611a7bf686cb890b8db38ad9ce1a5bbb'
        CRYPT_KEY: 'iuh213iu78ads898213euwioadjbxhjy-jkldHJKDJ_ksahdKASGDSAKDH32L4EJLDSACKÖÄASPOE24'
        SENTRY_KEY: 'https://fcdde304c3344126b70b8f8365df7650:1ef8823d9153412a9f77250fa9d45235@sentry.io/240812'
        SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
        FILES_SERVICE: 'local'
        AUTH_DEBUG: '0'
        TWITTER_ID: '764738293347024896'
        TWITTER_KEY: 'G6PfK0VGgF1GFYROic4hSAcAr'
        TWITTER_SECRET: 'imPH3BmKlk3XWzKY2DrcAXbll329NNwASRxgLK1Fw52pns2oGP'
        GOOGLE_ID: '1069128037243-4cua499nu3jf64l2q4irms93pmh7trsk.apps.googleusercontent.com'
        GOOGLE_SECRET: 'd59PePUgDSCGgB_JuxGerScB'
        FACEBOOK_ID: '153117502101937'
        FACEBOOK_SECRET: 'f1c03b95bfc5c671085147b31b0474ef'
        MAIL_DISPATCHER_URL: 'https://rg3k934ed5.execute-api.eu-central-1.amazonaws.com/prod'
        MAIL_DISPATCHER_API_KEY: 'ItgiwKjkDM9OxQ3Vyz0dC8uPwXMc9wJM3WvBsRyM'
        SUBSCRIPTION_SERVICE_URL: 'https://szwbyeo01a.execute-api.eu-central-1.amazonaws.com/prod'
        SUBSCRIPTION_SERVICE_API_KEY: 'tWDSmhCSPH1m6KIFN1UiE8S458Ai0OUS8UWYvm35'
        
