version: '2.3'

services:
#  mongo1:
#    restart: always
#    image: mongo:3.4
#    hostname: mongo1
#    expose:
#      - "27017"
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo1:/data/db

  mysql1:
    container_name: spreadshare-mysql1
    build: docker/mysql
    restart: always
    hostname: mysql1
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./application/schemas/structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./application/schemas/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    env_file:
        - variables.env

  memcached:
    container_name: spreadshare-memcached1
    restart: always
    hostname: memcached
    image: memcached:1.5.2
    ports:
      - "11211:11211"

  #queue:
  #  container_name: spreadshare-queue1
  #  restart: always
  #  image: phalconphp/beanstalkd:1.10
  #  ports:
  #    - "11300:11300"
  #  volumes:
  #    - beanstalk:/var/lib/beanstalkd

  redis:
    container_name: spreadshare-redis1
    restart: always
    hostname: redis
    image: redis:4.0
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  elasticsearch:
    container_name: spreadshare-elastic1
    image: elasticsearch:5
    restart: always
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - variables.env
    mem_limit: 2000000000

  app:
    build: docker/app
    container_name: spreadshare-backend1
    restart: always
    hostname: spreadshare
    working_dir: /project
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - .:/project
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
      - ./docker/apache2:/etc/apache2/spreadshare
    links:
      - "redis:redis"
      - "memcached:memcached"
#      - "mongo1:mongo1"
#      - "elasticsearch:elasticsearch"
    depends_on:
      - mysql1
      - redis
      - memcached
#      - queue1
#      - elasticsearch1
    env_file:
      - variables.env
    environment:
        BUILD_ENVIRONMENT: 'development'
        APPLICATION_ENV: 'development'
        HOST: 'spreadshare.javisantos.com:81'
        AUTH_CALLBACK: 'http://spreadshare.javisantos.com:81/login'
        WALLET: 'localhost'
        MAILGUN_KEY: 'key-611a7bf686cb890b8db38ad9ce1a5bbb'
        CRYPT_KEY: 'iuh213iu78ads898213euwioadjbxhjy-jkldHJKDJ_ksahdKASGDS$AKDH32L4EJLDSACKÖÄASPOE24'
        SENTRY_KEY: 'https://fcdde304c3344126b70b8f8365df7650:1ef8823d9153412a9f77250fa9d45235@sentry.io/240812'
        SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
        FILES_SERVICE: 'local'
        AUTH_DEBUG: '1'
        TWITTER_ID: '764738293347024896'
        TWITTER_KEY: 'Fv0eIOgtYNlMcAb81F6Q64Scq'
        TWITTER_SECRET: 'dIFZafw3ictdyREl5mva0WLHchaEUrdl0kZisPb6OCEfCSknCj'
        GOOGLE_ID: '102427747011-eakc8maf0t3apkfrrv196i12rf0f1edg.apps.googleusercontent.com'
        GOOGLE_SECRET: '8jLEm_zY8VnuNs4zAQ0SJiUX'
        FACEBOOK_ID: '153117502101937'
        FACEBOOK_SECRET: 'f1c03b95bfc5c671085147b31b0474ef'

volumes:
#  mongo1:
#    driver: local
  mysql:
    driver: local
  #beanstalk:
  #  driver: local
  redis:
    driver: local
#  esdata:
#    driver: local
