version: '2.3'

services:
#  mongo1:
#    restart: always
#    image: mongo:3.4
#    hostname: mongo1
#    expose:
#      - "27017"
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo1:/data/db

  mysql1:
    container_name: spreadshare-mysql1
    build: docker/mysql
    restart: always
    hostname: mysql1
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./application/schemas/mysql.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - variables.env

  memcached:
    container_name: spreadshare-memcached1
    restart: always
    hostname: memcached
    image: memcached:1.5.2
    ports:
      - "11211:11211"

  #queue:
  #  container_name: spreadshare-queue1
  #  restart: always
  #  image: phalconphp/beanstalkd:1.10
  #  ports:
  #    - "11300:11300"
  #  volumes:
  #    - beanstalk:/var/lib/beanstalkd

  redis:
    container_name: spreadshare-redis1
    restart: always
    hostname: redis
    image: redis:4.0
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

#  elasticsearch:
#    image: elasticsearch:5
#    restart: always
#    expose:
#      - "9200"
#      - "9300"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    env_file:
#      - variables.env
#    volumes:
#      - esdata:/usr/share/elasticsearch/data

  app:
    build: docker/app
    container_name: spreadshare-backend1
    restart: always
    hostname: spreadshare
    working_dir: /project
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - .:/project
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
      - ./docker/apache2:/etc/apache2/spreadshare
    links:
      - "redis:redis"
      - "memcached:memcached"
#      - "mongo1:mongo1"
#      - "elasticsearch:elasticsearch"
    depends_on:
      - mysql1
      - redis
      - memcached
#      - queue1
#      - elasticsearch1
    env_file:
      - variables.env
    environment:
        PRODUCTION: 'false'
        DEVELOPMENT: 'true'

volumes:
#  mongo1:
#    driver: local
  mysql:
    driver: local
  #beanstalk:
  #  driver: local
  redis:
    driver: local
#  esdata:
#    driver: local
